service: sport-widgets-test-test

provider:
    name: aws
    runtime: nodejs12.x
    region: eu-west-1
    stage: ${opt:stage, 'dev'}

plugins:
    - serverless-s3-sync

custom:
    config: ${file(./config.json)}
    bucketName: football-widget-test-${self:provider.stage}
    s3Sync:
        - bucketName: ${self:custom.bucketName}
          deleteRemoved: true
          acl: public-read
          localDir: build/
          params: # optional
            - index.html:
                CacheControl: 'no-cache'

resources:
  Resources:
    SportWidgetBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: ${self:custom.bucketName}
            AccessControl: PublicRead
            WebsiteConfiguration:
                IndexDocument: index.html
                ErrorDocument: index.html
        DeletionPolicy: ${self:custom.config.${self:provider.stage}.deletionPolicy}
    S3AccessPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
            Bucket:
                Ref: SportWidgetBucket
            PolicyDocument:
                Statement:
                    - Sid: PublicReadGetObject
                      Effect: Allow
                      Principal: '*'
                      Action:
                          - s3:GetObject
                      Resource: arn:aws:s3:::${self:custom.bucketName}/*

    CloudFrontDistribution:
            Type: AWS::CloudFront::Distribution
            Properties:
                DistributionConfig:
                    Origins:
                        - DomainName: ${self:custom.bucketName}.s3.amazonaws.com
                          Id: WidgetApp
                          CustomOriginConfig:
                              HTTPPort: 80
                              HTTPSPort: 443
                              OriginProtocolPolicy: https-only
                    Enabled: 'true'
                    DefaultRootObject: index.html
                    CustomErrorResponses:
                        - ErrorCode: 404
                          ResponseCode: 200
                          ResponsePagePath: /index.html
                    DefaultCacheBehavior:
                        AllowedMethods:
                            - DELETE
                            - GET
                            - HEAD
                            - OPTIONS
                            - PATCH
                            - POST
                            - PUT
                        TargetOriginId: WidgetApp
                        ForwardedValues:
                            QueryString: 'false'
                            Cookies:
                                Forward: none
                        ViewerProtocolPolicy: redirect-to-https
                    ViewerCertificate:
                        CloudFrontDefaultCertificate: true