version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0
jobs:
  build:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - run: mkdir bucket && echo "lorem ipsum sssssss" > bucket/build_asset.txt

  build-dev:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: bucket
          to: 's3://$S3_BUCKET_NAME-dev/prefix'

  build_prod:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: bucket
          to: 's3://$S3_BUCKET_NAME-prod/prefix'

workflows:
  dev-deploy:
    jobs:
      - build_dev:
          filters:
            branches:
              only: /develop/
  prod-deploy:
    jobs:
      - build
      - build_prod:
          filters:
            branches:
              only: /master/