version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0

executors:
  my-executor:
    docker:
      - image: 'cimg/python:3.6'
    working_directory: ~/repo


jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run: mkdir bucket && echo "lorem ipsum" > bucket/build_asset.txt
      - persist_to_workspace:
          root: .
          paths:
            - bucket

  build_dev:
    executor: my-executor
    steps:
      - attach_workspace:
          at: .
      # - run: |
      #     if [[ `cat ~/repo/bucket/build_asset.txt` == "lorem ipsum" ]]; then
      #       echo "It worked!";
      #     else
      #       echo "Nope!"; exit 1
      #     fi
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: bucket
          to: 's3://widget-table/prefix'

  build_prod:
    executor: my-executor
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: mkdir bucket && echo "lorem ipsum" > bucket/build_asset.txt
      # - run: |
      #     if [[ `cat ~/repo/bucket/build_asset.txt` == "lorem ipsum" ]]; then
      #       echo "It worked!";
      #     else
      #       echo "Nope!"; exit 1
      #     fi
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: bucket
          to: 's3://widget-table/prefix'

workflows:
  dev-deploy:
    jobs:
      - build_dev:
          filters:
            branches:
              only: /develop/
  prod-deploy:
    jobs:
      - build
      - build_prod:
          filters:
            branches:
              only: /master/