version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0

executors:
  my-executor:
    docker:
      - image: circleci/node:12.9.1-browsers
      - image: 'cimg/python:3.6'
    working_directory: ~/repo


jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - build

  build_dev:
    executor: my-executor
    steps:
      - attach_workspace:
          at: .
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: build
          to: 's3://$S3_BUCKET_NAME-dev/prefix'

  build_prod:
    executor: my-executor
    steps:
      - attach_workspace:
          at: .
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: build
          to: 's3://$S3_BUCKET_NAME-prod/prefix'

workflows:
  dev-deploy:
    jobs:
      - build_dev:
          requires:
            - build
          filters:
            branches:
              only: /develop/
  prod-deploy:
    jobs:
      - build
      - build_prod:
          requires:
            - build
          filters:
            branches:
              only: /master/